openapi: 3.0.0
info:
  title: Simple Test API
  version: 1.0.0
paths:
  /test:
    get:
      summary: A simple test endpoint
      operationId: getTestMessage
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello from the plugin!
